import { NextRequest, NextResponse } from 'next/server';

// Philippine schools dataset (major public and private schools by region)
const PH_SCHOOLS = [
  // NCR - Metro Manila
  'Ateneo de Manila University - Grade School',
  'Ateneo de Manila University - Junior High School',
  'Ateneo de Manila University - Senior High School',
  'De La Salle Santiago Zobel School',
  'De La Salle University Integrated School',
  'Miriam College Grade School',
  'Miriam College High School',
  'Paref Southridge School',
  'Paref Woodrose School',
  'Xavier School - San Juan',
  'Xavier School - Nuvali',
  'International School Manila',
  'British School Manila',
  'Saint Pedro Poveda College',
  'St. Paul College Pasig',
  'Lourdes School of Mandaluyong',
  'Lourdes School Quezon City',
  'La Salle Green Hills',
  'San Beda College Alabang',
  'San Beda University - Manila',
  'Colegio de San Juan de Letran',
  'University of Santo Tomas - Grade School',
  'University of Santo Tomas - Junior High School',
  'University of Santo Tomas - Senior High School',
  'University of the Philippines Integrated School',
  'Philippine Science High School - Main Campus',
  'Philippine Science High School - Bicol Region',
  'Philippine Science High School - Cagayan Valley',
  'Philippine Science High School - CALABARZON',
  'Philippine Science High School - Central Luzon',
  'Philippine Science High School - Central Mindanao',
  'Philippine Science High School - Eastern Visayas',
  'Philippine Science High School - Ilocos Region',
  'Philippine Science High School - Soccsksargen',
  'Philippine Science High School - Southern Mindanao',
  'Philippine Science High School - Western Visayas',
  'Manila Science High School',
  'Quezon City Science High School',
  'Valenzuela City School of Mathematics and Science',
  'Marikina Science High School',
  'Makati Science High School',
  'Pasig City Science High School',
  'Muntinlupa Science High School',
  'Taguig Science High School',
  'Caloocan City Science High School',
  'Las Piñas City National Science High School',
  'Malabon National Science High School',
  'Navotas National Science High School',
  'Mandaluyong Science High School',
  'San Juan National Science High School',
  'Parañaque National High School - SHS',
  'Claro M. Recto High School',
  'Araneta High School',
  'Manuel L. Quezon High School',
  'Commonwealth High School',
  'Diliman Preparatory School',
  'Holy Spirit National High School',
  'Camp Crame High School',
  'Gen. Pio del Pilar National High School',
  'Eulogio "Amang" Rodriguez Institute of Science and Technology',
  'Pasay City National Science High School',
  'Roosevelt College - Marikina',
  'Roosevelt College - Cubao',
  'Roosevelt College - Rodriguez',
  'Don Bosco Technical College - Mandaluyong',
  'Don Bosco Technical Institute - Makati',
  'Don Bosco School - Manila',
  'St. Mary\'s College - Quezon City',
  'St. Mary\'s College - Pasay',
  'Assumption College - San Lorenzo',
  'Assumption Antipolo',
  'Reedley International School',
  'PAREF - Northfield School',
  'PAREF - South Crest School',
  'PAREF - Springdale School',
  'PAREF - Rosehill School',
  // CALABARZON
  'University of the Philippines Rural High School - Laguna',
  'Laguna College',
  'Canossa School - Santa Rosa',
  'Don Bosco College - Canlubang',
  'Colegio San Agustin - Biñan',
  'Southville International School and Colleges',
  'Faith Christian School - Batangas',
  'De La Salle Lipa - Integrated School',
  'University of Batangas - Grade School',
  'St. Bridget College - Batangas',
  'Jacobo Z. Gonzales Memorial School',
  'Cavite National High School',
  'Imus National High School',
  'Dasmarinas Integrated High School',
  'General Mariano Alvarez Technical High School',
  'Bacoor National High School',
  'Tanza National High School',
  'Naic National High School',
  'Rosario National High School',
  'Mendez National High School',
  'Tagaytay City National High School',
  // Central Luzon
  'Angeles University Foundation - Grade School',
  'Holy Angel University - Basic Education',
  'Angeles City Science High School',
  'Clark International School',
  'Don Honorio Ventura State University - High School',
  'Pampanga High School',
  'Mabalacat National High School',
  'San Fernando Elementary School',
  'Mimosa Plus International School',
  'Bulacan State University - Laboratory High School',
  'Marcelo H. del Pilar National High School',
  'Baliuag University - Grade School',
  'St. Paul University Philippines - Tuguegarao',
  'Tarlac National High School',
  'Tarlac State University - Laboratory High School',
  'Olongapo City National High School',
  'Zambales National High School',
  'Nueva Ecija High School',
  'Cabanatuan City Science High School',
  // Davao Region
  'Philippine Science High School - Southern Mindanao Campus',
  'Davao City National High School',
  'Ateneo de Davao University - Grade School',
  'Ateneo de Davao University - Junior High School',
  'University of the Philippines Mindanao - SHS',
  'Davao Christian High School',
  'St. Mary\'s College of Tagum',
  'Holy Cross of Davao College',
  'University of Mindanao - Grade School',
  'Mintal Comprehensive High School',
  'F. Bustamante National High School',
  'Daniel R. Aguinaldo National High School',
  // Western Visayas
  'University of the Philippines Visayas - High School',
  'Philippine Science High School - Western Visayas Campus',
  'University of San Agustin - Basic Education',
  'Ateneo de Iloilo - Santa Maria Catholic School',
  'Iloilo National High School',
  'West Visayas State University - Laboratory High School',
  'St. Paul University Iloilo - Grade School',
  'St. Scholastica\'s Academy - Bacolod',
  'University of St. La Salle - Integrated School',
  'Bacolod City National High School',
  'Negros Occidental National Science High School',
  'La Salle Academy - Iloilo',
  // Central Visayas
  'University of the Philippines Cebu - SHS',
  'Philippine Science High School - Central Visayas Campus',
  'Cebu City National Science High School',
  'University of San Carlos - Basic Education',
  'University of San Jose-Recoletos - Grade School',
  'Ateneo de Cebu - Grade School',
  'Ateneo de Cebu - Junior High School',
  'Ateneo de Cebu - Senior High School',
  'St. Theresa\'s College - Cebu City',
  'Colegio de la Inmaculada Concepcion - Cebu',
  'University of the Visayas - Grade School',
  'Cebu Normal University - Integrated Laboratory School',
  'Don Bosco Technology Center - Cebu',
  'Sacred Heart School - Ateneo de Cebu',
  'Holy Cross of Davao College',
  'Mandaue City Science High School',
  'Lapu-Lapu City National High School',
  'Talisay City National High School',
  'Bohol National High School',
  'Tagbilaran City Science High School',
  // Northern Luzon (Cordillera)
  'Baguio City National Science High School',
  'University of the Philippines Baguio - SHS',
  'Saint Louis University - Laboratory High School',
  'Brent International School Baguio',
  'Philippine Military Academy - High School',
  'Baguio City High School',
  'Benguet National High School',
  'La Trinidad National High School',
  'Apayao National High School',
  'Kalinga National High School',
  // Bicol Region
  'Ateneo de Naga University - Grade School',
  'Ateneo de Naga University - Junior High School',
  'Naga City Science High School',
  'University of Nueva Caceres - Grade School',
  'University of the Philippines Bicol - SHS',
  'Philippine Science High School - Bicol Region Campus',
  'Legazpi City Science High School',
  'Mariners Polytechnic College - Basic Education',
  'Daraga National High School',
  'Sorsogon National High School',
  'Catanduanes National High School',
  'Masbate National High School',
  // Eastern Visayas
  'Leyte National High School',
  'Tacloban City National High School',
  'Philippine Science High School - Eastern Visayas Campus',
  'University of the Philippines Tacloban - SHS',
  'St. Scholastica\'s College Tacloban',
  'Leyte Normal University - Integrated Laboratory School',
  'Samar National School',
  'Southern Leyte National High School',
  'Eastern Samar National Comprehensive High School',
  'Biliran National High School',
  // Zamboanga Peninsula
  'Zamboanga City National High School',
  'Zamboanga Sibugay National High School',
  'Ateneo de Zamboanga University - Grade School',
  'Ateneo de Zamboanga University - Junior High School',
  'Western Mindanao State University - SHS',
  'Philippine Science High School - Zamboanga Peninsula Campus',
  'Universidad de Zamboanga - Grade School',
  'Dipolog City National High School',
  'Pagadian City National High School',
  // Northern Mindanao
  'Bukidnon National High School',
  'Malaybalay City National High School',
  'Philippine Science High School - Northern Mindanao Campus',
  'Central Mindanao University - Laboratory High School',
  'Xavier University - Ateneo de Cagayan - Grade School',
  'Xavier University - Ateneo de Cagayan - Junior High School',
  'Cagayan de Oro City National High School',
  'Misamis Oriental General Comprehensive High School',
  'Lourdes College - Grade School',
  'Corpus Christi School - Cagayan de Oro',
  'Lanao del Norte National High School',
  'Iligan City National High School',
  'Mindanao State University - Iligan Institute of Technology - SHS',
  'Bukidnon State University - Laboratory High School',
  // SOCCSKSARGEN
  'Notre Dame of Dadiangas University - Grade School',
  'Notre Dame of Dadiangas University - Junior High School',
  'General Santos City National High School',
  'Philippine Science High School - Soccsksargen Campus',
  'Cotabato City National High School',
  'Notre Dame University - Grade School',
  'Koronadal National High School',
  'Tacurong National High School',
  'South Cotabato National High School',
  'Sultan Kudarat National High School',
  'Kidapawan City National High School',
  // ARMM / BARMM
  'Mindanao State University - Marawi - SHS',
  'MSU - Lanao National High School',
  'Notre Dame - Siena College of General Santos',
  'Maguindanao National High School',
  'Tawi-Tawi National High School',
  'Sulu National High School',
  'Basilan National High School',
  // CARAGA
  'Butuan City National High School',
  'Surigao City National High School',
  'Agusan National High School',
  'Philippine Science High School - Caraga Campus',
  'Caraga State University - Laboratory High School',
  'Surigao del Sur National High School',
  'Agusan del Sur National High School',
  'Dinagat Islands National High School',
  // MIMAROPA
  'Palawan National High School',
  'Puerto Princesa City National High School',
  'Occidental Mindoro National High School',
  'Oriental Mindoro National High School',
  'Marinduque National High School',
  'Romblon National High School',
];

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const query = searchParams.get('q')?.toLowerCase().trim() ?? '';

    if (query.length < 2) {
      return NextResponse.json([]);
    }

    const results = PH_SCHOOLS.filter((school) =>
      school.toLowerCase().includes(query)
    ).slice(0, 20);

    return NextResponse.json(results);
  } catch (error) {
    console.error('Schools search error:', error);
    return NextResponse.json({ error: 'Search failed' }, { status: 500 });
  }
}